### ISSUE TITLE
ERROR: CD-HIT is not installed or not included in the path.

### ISSUE THREAD

**Issue by ibseq** [MigleSur/GenAPI#10]
Hello
what does this error mean and how can I fix it?

thanks!
ibseq

**Comment by MigleSur** [comment]
Dear Ibseq,

I am happy you found GenAPI interesting. The error means that CD-HIT software, which is necessary for GenAPI to work, is not available in your system. After you install it, you should be able to successfully run GenAPI.

Best,
Migle
