### ISSUE TITLE
Error option -m

### ISSUE THREAD

**Issue by ireneortega** [MigleSur/GenAPI#11]
I run GenAPI with `-m `option, but I got this error:

```
-----PLOTTING GENE PRESENCE-ABSENCE HEATMAPS-----
Error in cut.default(x, breaks = breaks, include.lowest = T) : 
  'breaks' are not unique
Calls: pheatmap ... scale_colours -> matrix -> scale_vec_colours -> cut -> cut.default
Execution interrupted
```

What went wrong?

**Comment by MigleSur** [comment]
Dear ireneortega,

Sorry for my late reply.  I am happy to hear that you are interested in using GenAPI. I need more information about the error you're getting. Does the `-m` option work with the test dataset? Also, could you share the gene presence-absence matrix with me (migle.gabrielaite@regionh.dk) so I could look into the file and try to reproduce the error?

Best,
Migle

**Comment by ireneortega** [comment]
Sorry for the delay, I was working on other tools, but I recently come back to GenAPI again for my research and I notice I opened this issue without answering. In fact I have no idea what caused the problem but I figured out that pheatmap library was not installed in the virtual machine. I've just run it again now with no problems!
