### ISSUE TITLE
awk error on custom gff files

### ISSUE THREAD

**Issue by vbonnici** [MigleSur/GenAPI#13]
I'm trying to run genapi one some gff files of mine, that I produced via prodigal.
The script gene_ad_alignemt_against_seq.sh throws several errors, many of which at line 164.
The files are available at https://github.com/vbonnici/genapit_test
Please, can you help me?

**Comment by MigleSur** [comment]
Dear vbonnici,

I am happy to hear that you are interested in GenAPI. I tried to replicate your error but unsuccessfully. What system are you trying to run GenAPI on? Also, did you successfully run GenAPI analysis on the test dataset? Finally, you should check your ID names in gff files to make them unique within and between files.

**Comment by MigleSur** [comment]
Closing as it is outdated.
