### ISSUE TITLE
Is it normal for the runtime to be extremely long?

### ISSUE THREAD

**Issue by Dx-wmc** [MigleSur/GenAPI#19]
Hi, I tried to use genapi for gene presence and loss analysis and noticed that it takes over an hour to process just 8 GFF files. Is this a typical runtime? For roary or other tools, it just takes a few minutes.

**Comment by MigleSur** [comment]
Essentially, yes. Roary works in a completely different way. Also, GenAPI could use some optimization but, unfortunately, I cannot prioritize it now.
