### ISSUE TITLE
error runing genapi 

### ISSUE THREAD

**Issue by pavlo888** [MigleSur/GenAPI#2]
Hi there, 

I got the following error when running genapi and I am not sure how to solve it: 

(genapi) Pablos-MacBook-Air:genapitest pablov$ genapi -n test
sed: 1: "/##FASTA/Q": invalid command code Q

Any idea? 

Thanks. 

Pablo

**Comment by MigleSur** [comment]
Hi Pablo,

Happy that you found GenAPI interesting! 

Does your GFF file has a FASTA genome sequence at the end of the file? If not, you should merge an annotation GFF file with a FASTA sequence (##FASTA and all genome sequence starting from the new line). Here you can find more information about GFF files: https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md

If your GFF file is annotated with the genome sequence, let me know and I will look at the code.

Migle

**Comment by pavlo888** [comment]
Hi Migle,

Thank you for your prompt response. I have checked the .gff input files and
they do contain the FASTA sequences at the end of the file. The gff files I
am using are the ones I have obtained from running Prokka. Any other ideas
of what the issue might be?

Cheers,
Pablo

**Comment by MigleSur** [comment]
Hi Pablo,

Sorry for a late reply. I think, I finally figured out what went wrong. Apparently, sed function doesn't have a "Q" option on Mac OS but it is fully functional on UNIX. I have changed the script now and it should be (fingers crossed) compatible with both Mac OS and UNIX. 

Best,
Migle

**Comment by pavlo888** [comment]
Hi Migle,

Thanks a lot! I will try it out this week and let you know.

Cheers,
Pablo

**Comment by pavlo888** [comment]
Hi Migle,

Unfortunately, I cannot run it. There seems to be a different error this
time.

So, to give you some context: I created an anaconda environment containing
all the required dependencies for GenAPI to work properly. Then I activate
the environment, place the gff files in the GenAPI/bin folder and then run
the executable bash file.

(genapi) MacBook-Air:bin pablov$ /Users/pablov/Downloads/GenAPI/bin/genapi

Warning: The following lines have no ID and will be excluded from the
analysis:

NC_012967.1 minced:0.1.6 repeat_region 2772561 2772833 5 . .
rpt_family=CRISPR

sed: 1: "./REL606_temp.tsv": invalid command code .

**Comment by MigleSur** [comment]
Dear Pablo,

Sorry for taking so long to reply to your messages. I originally work on UNIX system which makes it harder to troubleshoot for the sed issues related to Mac OS. 

I now tried looking at it and it seems like the sed -i is triggering the error. Could you try to change ```sed -i "/$line/d" ${tsv_file}``` to ```sed -i '' "/$line/d" ${tsv_file}``` in the genapi script? I think this should do the trick for Mac OS. Unfortunately, there I can't find any universal solution for this problem.

Another option could be for you to use a UNIX machine to run the script. I know it's not optimal but I'm afraid that's all I can suggest.

Best,
Migle

**Comment by MigleSur** [comment]
Dear Pablo,

I was revisiting the issues you are having and it seems like the only way to make sure the code runs for your machine is to install GNU sed. More advice on how to deal with GNU sed on Mac OS X is here: https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-10-10-brew-install-default-names-no-longer-su 

Best,
Migle

**Comment by pavlo888** [comment]
Hi Migle,

Thank you very much for your help. I think it is easier if I just try it on
a Linux-running machine. I think I might have access to one soon enough and
I will definitely try your package and let you know how it goes.

Cheers,
Pablo
