### ISSUE TITLE
Customized heatmap image quality

### ISSUE THREAD

**Issue by Yasana1990** [MigleSur/GenAPI#21]
Hello! Thank you for your tool - it is very useful and neat. I have a question - is it possible to customize a heatmap image quality generated by GenAPI? By default it is quite low - I got an image 834x805 pixels but it would be great to have an oppurtunity to generate publication image quality (300 dpi). Is it possible? Thank you!

**Comment by MigleSur** [comment]
Hi, I am happy to hear that you find the tool useful. You can change the saved png parameters in the generate_heatmap_all.R/generate_heatmap_missing.R script to get better-quality figures. Hope that helps, if not, feel free to write me an e-mail or open a new issue to help navigate it.
