### ISSUE TITLE
Syntax error on gene_db_alignment_against_seq.sh 

### ISSUE THREAD

**Issue by pavlo888** [MigleSur/GenAPI#3]
Hi Migle, 

I have been able to run the GenAPI pipeline, however it comes to a point when it shows the following error: 

gene_db_alignment_against_seq.sh: 1: gene_db_alignment_against_seq.sh: Syntax error: redirection unexpected

Could you help me solve this issue? 

Cheers, 
Pablo

**Comment by MigleSur** [comment]
Hi Pablo,

Most probably your default shell is not bash. I changed the script so now there is no ambiguity. Try cloning the repo again and rerun the script.

Best,
Migle
