### ISSUE TITLE
Phylogenetic tree 

### ISSUE THREAD

**Issue by PatoUru** [MigleSur/GenAPI#4]
Hi All!
I would like to know how  the phylogenetic tree is built. The only information provided is that the presence and absence of genes is used. 
So .. the phylogenetic tree is built by aligning the core gene?
Thank you!!
Pato

**Comment by MigleSur** [comment]
Dear Pato,

Thanks for the interest in GenAPI. The phylogenetic tree is built by using the gene presence-absence matrix as an input for RAxML. So, the phylogenetic tree is actually estimated from the GenAPI output and no additional alignment is performed.

Hope that helps!

Best,
Migle

**Comment by ireneortega** [comment]
I have the same question. Attending to the phylogenetic_analysis.sh file, how is the ${NAME}_binary_alignments.fasta file generated? This file contains the alignment that is used for the construction of the phylogenetic tree by RAxML.

After comment the line referring to remove tmp file in genapi file, I realise that the content of the (...)alignment.fasta file is exactly the same as the gene_presence_absence_[name].txt file. So as @MigleSur said, the gene presence-absence matrix (core and accessory genome) is used to build the phylogenetic tree, that in fact, I think it is reduced to the the accessory genome only as values equal to 1 in all genomes do not add information for the phylogenetic tree. Do you agree?
