### ISSUE TITLE
sh: 0: Can't open settings.sh

### ISSUE THREAD

**Issue by Adarsh931** [MigleSur/GenAPI#6]
Hi,
I have installed everything properly, and even kept the location in PATH, but I keep getting this error.
sh: 0: Can't open settings.sh

I am running this command from terminal:
genapi -p 24 -n A10vsGB_analysis -t -m

RE system: I am using Ubuntu 18.04.4 LTS. 

Please help me out.

**Comment by Adarsh931** [comment]
I was able to solve this problem by changing a line in genapi file.
Original: sh settings.sh ......
Changed: sudo full/path/to/settings.sh ......

Also, remove any space in file name.

**Comment by ryu1013** [comment]
I had the same issue as you. I fixed it, changing the below line in the genapi file that is located in /GenAPI/bin. 
The command "sh" was just replaced with "bash". I thought the command sh has the same function as the command bash...... But, there's something interrupting.

Original: 
# printing all the settings to a settings file

**_sh_** settings.sh $NAME $THREADS $ALIGNMENT_COVERAGE $IDENTITY $geneCov1 $geneCov2 $geneIden1 $gen>
``



Changed: 
# printing all the settings to a settings file

_**bash**_ settings.sh $NAME $THREADS $ALIGNMENT_COVERAGE $IDENTITY $geneCov1 $geneCov2 $geneIden1 $gen>
