### ISSUE TITLE
Comparison of CDs

### ISSUE THREAD

**Issue by ardy20** [MigleSur/GenAPI#9]
Hi
Could this tool be used for comparison of CDS (produced by structural annotation) in plants? For example, CDS1 vs CDS2?
Could you also please example command for this? How does the tool pick up the CDS1 and CDS2?
Regards

**Comment by MigleSur** [comment]
Hi, 

Thanks for your interesti in GenAPI. GenAPI is developed for bacterial genome analysis and, therefore, cannot be applied to plant genomics. 

Best,
Migle
